version: '3'
services:
  fastapi_model:
    build: .
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  load_balancer:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - fastapi_model
    networks:
      - mynetwork

networks:
  mynetwork:
