version: "3.9"

services:
  fastapi-app:
    build: .
    container_name: fastapi-gpu
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./audios:/app/audios
    runtime: nvidia
