version: "3.9"

services:
  fastapi-app:
    build: .
    container_name: fastapi-gpu
    expose:
      - "8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    volumes:
      - ./audios:/app/audios
    runtime: nvidia
